"""added language to articles

Revision ID: 0e7d250942d9
Revises: 3b97d2a45bb3
Create Date: 2018-03-15 18:34:57.300140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7d250942d9'
down_revision = '3b97d2a45bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'language')
    # ### end Alembic commands ###
