"""added about me and last login to users

Revision ID: 3b97d2a45bb3
Revises: 3140fab4a0be
Create Date: 2018-03-07 15:24:43.225102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b97d2a45bb3'
down_revision = '3140fab4a0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
